### ISSUE TITLE
/ (aka: the front door)

### ISSUE THREAD

**Issue by ghost** [Nimmard/django-blog#2]
Our users must be able to intuitively navigate to the correct location they are seeking
so we must present an obvious front door and a helpful lobby.

- [x] Pages Controller
  - [x] Lobby Template
  - [x] Welcome message.
  - [x] Message of the day.
  - [x] In the news
  - [x] About
  - [x] Blurbs
- [x] Global Navigation
  - [x] Root
  - [x] Wishlist
  - [x] Blog
  - [x] Admin?
- [x] Active path highlighting.

**Comment by BadQuanta** [comment]
I don't think #5 closes this issue yet... but is a good first step.
